"""drop unique constraint from board_members.board_id


Revision ID: 03c072b4a848
Revises: 43dd80683fab
Create Date: 2026-02-01 20:07:22.546851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c072b4a848'
down_revision: Union[str, Sequence[str], None] = '43dd80683fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=True)
    # ### end Alembic commands ###
