"""unique constaints for the models Columns and BoardMembers

Revision ID: 347cdf4402a7
Revises: bfd2632b456d
Create Date: 2026-02-02 22:15:37.308001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347cdf4402a7'
down_revision: Union[str, Sequence[str], None] = 'bfd2632b456d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('board_members_board_id_user_id_key'), 'board_members', type_='unique')
    op.create_unique_constraint('uq_member_per_board', 'board_members', ['board_id', 'user_id'])
    op.create_unique_constraint('uq_column_name_per_board', 'columns', ['board_id', 'name'])
    op.create_unique_constraint('uq_column_position_per_board', 'columns', ['board_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_column_position_per_board', 'columns', type_='unique')
    op.drop_constraint('uq_column_name_per_board', 'columns', type_='unique')
    op.drop_constraint('uq_member_per_board', 'board_members', type_='unique')
    op.create_unique_constraint(op.f('board_members_board_id_user_id_key'), 'board_members', ['board_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
