"""Dropped id from board members and added Unique constaint

Revision ID: 43dd80683fab
Revises: 9f8274ead72e
Create Date: 2026-01-28 21:20:47.255377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43dd80683fab'
down_revision: Union[str, Sequence[str], None] = '9f8274ead72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board_members', ['board_id', 'user_id'])
    op.drop_column('board_members', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_members', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'board_members', type_='unique')
    # ### end Alembic commands ###
