"""swapped position to be Decimal

Revision ID: 21ff5d97f5f4
Revises: d033781d19bd
Create Date: 2026-02-02 21:11:25.412874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ff5d97f5f4'
down_revision: Union[str, Sequence[str], None] = 'd033781d19bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'position',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'position',
               existing_type=sa.DECIMAL(precision=10, scale=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
