"""columns table

Revision ID: 85ce8cbc0a50
Revises: 2fd1fb2387ee
Create Date: 2026-01-27 18:32:31.559047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ce8cbc0a50'
down_revision: Union[str, Sequence[str], None] = '2fd1fb2387ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('columns',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('board_members_user_id_fkey'), 'board_members', type_='foreignkey')
    op.drop_constraint(op.f('board_members_board_id_fkey'), 'board_members', type_='foreignkey')
    op.create_foreign_key(None, 'board_members', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'board_members', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_members', type_='foreignkey')
    op.drop_constraint(None, 'board_members', type_='foreignkey')
    op.create_foreign_key(op.f('board_members_board_id_fkey'), 'board_members', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(op.f('board_members_user_id_fkey'), 'board_members', 'user', ['user_id'], ['id'])
    op.drop_table('columns')
    # ### end Alembic commands ###
