""".

Revision ID: bfd2632b456d
Revises: 21ff5d97f5f4
Create Date: 2026-02-02 22:10:27.391649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd2632b456d'
down_revision: Union[str, Sequence[str], None] = '21ff5d97f5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('columns', 'position',
               existing_type=sa.NUMERIC(precision=10, scale=20),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('tasks', 'position',
               existing_type=sa.NUMERIC(precision=10, scale=20),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'position',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=20),
               existing_nullable=False)
    op.alter_column('columns', 'position',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=20),
               existing_nullable=False)
    # ### end Alembic commands ###
