"""added relathionship between tasks and board

Revision ID: ce99803ab0dd
Revises: 347cdf4402a7
Create Date: 2026-02-03 22:32:25.796600

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ce99803ab0dd"
down_revision: Union[str, Sequence[str], None] = "347cdf4402a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("board_id", sa.Integer(), nullable=False))
    op.add_column("tasks", sa.Column("assignee_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("tasks_column_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "user", ["assignee_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "tasks", "columns", ["column_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "tasks", "boards", ["board_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_column_id_fkey"),
        "tasks",
        "columns",
        ["column_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("tasks", "assignee_id")
    op.drop_column("tasks", "board_id")
    # ### end Alembic commands ###
